/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * How payment is collected. `automatic` for checkout, `manual` for invoices.
 */
export enum CollectionMode2 {
    Automatic = "automatic",
    Manual = "manual",
}
