/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Represents a customer entity.
 */
export class CustomerCreate extends SpeakeasyBase {
    /**
     * Email address for this entity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * Unique Paddle ID for this customer entity, prefixed with `ctm_`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * Valid IETF BCP 47 short form locale tag. If omitted, defaults to `en`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "locale" })
    locale?: string;

    /**
     * Full name.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
