/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { CurrencyCode2, CurrencyCode2$ } from "./currencycode2";
import { SchemaStatusDiscount, SchemaStatusDiscount$ } from "./schemastatusdiscount";
import { z } from "zod";

/**
 * Type of discount.
 */
export enum DiscountType {
    Flat = "flat",
    FlatPerSeat = "flat_per_seat",
    Percentage = "percentage",
}

/**
 * Represents a discount entity.
 */
export type Discount = {
    /**
     * Amount to discount by. For `percentage` discounts, must be an amount between `0.01` and `100`. For `flat` and `flat_per_seat` discounts, amount in the lowest denomination for a currency.
     */
    amount?: string | undefined;
    /**
     * Unique code that customers can use to apply this discount at checkout. Use letters and numbers only, up to 16 characters. Paddle generates a random 10-character code if a code is not provided and `enabled_for_checkout` is `true`.
     */
    code?: string | null | undefined;
    /**
     * RFC 3339 datetime string of when this entity was created. Set automatically by Paddle.
     */
    createdAt?: Date | undefined;
    /**
     * Supported three-letter ISO 4217 currency code.
     */
    currencyCode?: CurrencyCode2 | undefined;
    /**
     * Short description for this discount for your reference. Not shown to customers.
     */
    description?: string | undefined;
    /**
     * Whether this discount can be applied by a customer at checkout.
     */
    enabledForCheckout?: boolean | undefined;
    /**
     * RFC 3339 datetime string.
     */
    expiresAt?: Date | undefined;
    /**
     * Unique Paddle ID for this discount, prefixed with `dsc_`.
     */
    id?: string | undefined;
    /**
     * Amount of subscription billing periods that this discount recurs for. Requires `recur`. `null` if this discount recurs forever.
     */
    maximumRecurringIntervals?: number | null | undefined;
    /**
     * Whether this discount applies for multiple billing periods.
     */
    recur?: boolean | undefined;
    /**
     * Product or price IDs that this discount is for. When including a product ID, all prices for that product can be discounted. `null` if this discount applies to all products and prices.
     */
    restrictTo?: Array<string> | null | undefined;
    /**
     * Whether this entity can be used in Paddle. `expired` and `used` are set automatically by Paddle.
     */
    status?: SchemaStatusDiscount | undefined;
    /**
     * How many times this discount has been redeemed. Automatically incremented by Paddle when an order completes.
     */
    timesUsed?: number | undefined;
    /**
     * Type of discount.
     */
    type?: DiscountType | undefined;
    /**
     * RFC 3339 datetime string of when this entity was updated. Set automatically by Paddle.
     */
    updatedAt?: Date | undefined;
    /**
     * Maximum amount of times this discount can be used. This is an overall limit, rather than a per-customer limit. `null` if this discount can be used an unlimited amount of times.
     */
    usageLimit?: number | null | undefined;
};

/**
 * Represents a discount entity.
 */
export type DiscountInput = {
    /**
     * Amount to discount by. For `percentage` discounts, must be an amount between `0.01` and `100`. For `flat` and `flat_per_seat` discounts, amount in the lowest denomination for a currency.
     */
    amount?: string | undefined;
    /**
     * Unique code that customers can use to apply this discount at checkout. Use letters and numbers only, up to 16 characters. Paddle generates a random 10-character code if a code is not provided and `enabled_for_checkout` is `true`.
     */
    code?: string | null | undefined;
    /**
     * Supported three-letter ISO 4217 currency code.
     */
    currencyCode?: CurrencyCode2 | undefined;
    /**
     * Short description for this discount for your reference. Not shown to customers.
     */
    description?: string | undefined;
    /**
     * Whether this discount can be applied by a customer at checkout.
     */
    enabledForCheckout?: boolean | undefined;
    /**
     * RFC 3339 datetime string.
     */
    expiresAt?: Date | undefined;
    /**
     * Unique Paddle ID for this discount, prefixed with `dsc_`.
     */
    id?: string | undefined;
    /**
     * Amount of subscription billing periods that this discount recurs for. Requires `recur`. `null` if this discount recurs forever.
     */
    maximumRecurringIntervals?: number | null | undefined;
    /**
     * Whether this discount applies for multiple billing periods.
     */
    recur?: boolean | undefined;
    /**
     * Product or price IDs that this discount is for. When including a product ID, all prices for that product can be discounted. `null` if this discount applies to all products and prices.
     */
    restrictTo?: Array<string> | null | undefined;
    /**
     * Whether this entity can be used in Paddle. `expired` and `used` are set automatically by Paddle.
     */
    status?: SchemaStatusDiscount | undefined;
    /**
     * Type of discount.
     */
    type?: DiscountType | undefined;
    /**
     * Maximum amount of times this discount can be used. This is an overall limit, rather than a per-customer limit. `null` if this discount can be used an unlimited amount of times.
     */
    usageLimit?: number | null | undefined;
};

/** @internal */
export const DiscountType$ = z.nativeEnum(DiscountType);

/** @internal */
export namespace Discount$ {
    export type Inbound = {
        amount?: string | undefined;
        code?: string | null | undefined;
        created_at?: string | undefined;
        currency_code?: CurrencyCode2 | undefined;
        description?: string | undefined;
        enabled_for_checkout?: boolean | undefined;
        expires_at?: string | undefined;
        id?: string | undefined;
        maximum_recurring_intervals?: number | null | undefined;
        recur?: boolean | undefined;
        restrict_to?: Array<string> | null | undefined;
        status?: SchemaStatusDiscount | undefined;
        times_used?: number | undefined;
        type?: DiscountType | undefined;
        updated_at?: string | undefined;
        usage_limit?: number | null | undefined;
    };

    export const inboundSchema: z.ZodType<Discount, z.ZodTypeDef, Inbound> = z
        .object({
            amount: z.string().optional(),
            code: z.nullable(z.string()).optional(),
            created_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            currency_code: CurrencyCode2$.optional(),
            description: z.string().optional(),
            enabled_for_checkout: z.boolean().default(true),
            expires_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            id: z.string().optional(),
            maximum_recurring_intervals: z.nullable(z.number().int()).optional(),
            recur: z.boolean().default(false),
            restrict_to: z.nullable(z.array(z.string())).optional(),
            status: SchemaStatusDiscount$.optional(),
            times_used: z.number().int().optional(),
            type: DiscountType$.optional(),
            updated_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            usage_limit: z.nullable(z.number().int()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.amount === undefined ? null : { amount: v.amount }),
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.created_at === undefined ? null : { createdAt: v.created_at }),
                ...(v.currency_code === undefined ? null : { currencyCode: v.currency_code }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.enabled_for_checkout === undefined
                    ? null
                    : { enabledForCheckout: v.enabled_for_checkout }),
                ...(v.expires_at === undefined ? null : { expiresAt: v.expires_at }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.maximum_recurring_intervals === undefined
                    ? null
                    : { maximumRecurringIntervals: v.maximum_recurring_intervals }),
                ...(v.recur === undefined ? null : { recur: v.recur }),
                ...(v.restrict_to === undefined ? null : { restrictTo: v.restrict_to }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.times_used === undefined ? null : { timesUsed: v.times_used }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.updated_at === undefined ? null : { updatedAt: v.updated_at }),
                ...(v.usage_limit === undefined ? null : { usageLimit: v.usage_limit }),
            };
        });

    export type Outbound = {
        amount?: string | undefined;
        code?: string | null | undefined;
        created_at?: string | undefined;
        currency_code?: CurrencyCode2 | undefined;
        description?: string | undefined;
        enabled_for_checkout: boolean;
        expires_at?: string | undefined;
        id?: string | undefined;
        maximum_recurring_intervals?: number | null | undefined;
        recur: boolean;
        restrict_to?: Array<string> | null | undefined;
        status?: SchemaStatusDiscount | undefined;
        times_used?: number | undefined;
        type?: DiscountType | undefined;
        updated_at?: string | undefined;
        usage_limit?: number | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Discount> = z
        .object({
            amount: z.string().optional(),
            code: z.nullable(z.string()).optional(),
            createdAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            currencyCode: CurrencyCode2$.optional(),
            description: z.string().optional(),
            enabledForCheckout: z.boolean().default(true),
            expiresAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            id: z.string().optional(),
            maximumRecurringIntervals: z.nullable(z.number().int()).optional(),
            recur: z.boolean().default(false),
            restrictTo: z.nullable(z.array(z.string())).optional(),
            status: SchemaStatusDiscount$.optional(),
            timesUsed: z.number().int().optional(),
            type: DiscountType$.optional(),
            updatedAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            usageLimit: z.nullable(z.number().int()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.amount === undefined ? null : { amount: v.amount }),
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.createdAt === undefined ? null : { created_at: v.createdAt }),
                ...(v.currencyCode === undefined ? null : { currency_code: v.currencyCode }),
                ...(v.description === undefined ? null : { description: v.description }),
                enabled_for_checkout: v.enabledForCheckout,
                ...(v.expiresAt === undefined ? null : { expires_at: v.expiresAt }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.maximumRecurringIntervals === undefined
                    ? null
                    : { maximum_recurring_intervals: v.maximumRecurringIntervals }),
                recur: v.recur,
                ...(v.restrictTo === undefined ? null : { restrict_to: v.restrictTo }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.timesUsed === undefined ? null : { times_used: v.timesUsed }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.updatedAt === undefined ? null : { updated_at: v.updatedAt }),
                ...(v.usageLimit === undefined ? null : { usage_limit: v.usageLimit }),
            };
        });
}

/** @internal */
export namespace DiscountInput$ {
    export type Inbound = {
        amount?: string | undefined;
        code?: string | null | undefined;
        currency_code?: CurrencyCode2 | undefined;
        description?: string | undefined;
        enabled_for_checkout?: boolean | undefined;
        expires_at?: string | undefined;
        id?: string | undefined;
        maximum_recurring_intervals?: number | null | undefined;
        recur?: boolean | undefined;
        restrict_to?: Array<string> | null | undefined;
        status?: SchemaStatusDiscount | undefined;
        type?: DiscountType | undefined;
        usage_limit?: number | null | undefined;
    };

    export const inboundSchema: z.ZodType<DiscountInput, z.ZodTypeDef, Inbound> = z
        .object({
            amount: z.string().optional(),
            code: z.nullable(z.string()).optional(),
            currency_code: CurrencyCode2$.optional(),
            description: z.string().optional(),
            enabled_for_checkout: z.boolean().default(true),
            expires_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            id: z.string().optional(),
            maximum_recurring_intervals: z.nullable(z.number().int()).optional(),
            recur: z.boolean().default(false),
            restrict_to: z.nullable(z.array(z.string())).optional(),
            status: SchemaStatusDiscount$.optional(),
            type: DiscountType$.optional(),
            usage_limit: z.nullable(z.number().int()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.amount === undefined ? null : { amount: v.amount }),
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.currency_code === undefined ? null : { currencyCode: v.currency_code }),
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.enabled_for_checkout === undefined
                    ? null
                    : { enabledForCheckout: v.enabled_for_checkout }),
                ...(v.expires_at === undefined ? null : { expiresAt: v.expires_at }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.maximum_recurring_intervals === undefined
                    ? null
                    : { maximumRecurringIntervals: v.maximum_recurring_intervals }),
                ...(v.recur === undefined ? null : { recur: v.recur }),
                ...(v.restrict_to === undefined ? null : { restrictTo: v.restrict_to }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.usage_limit === undefined ? null : { usageLimit: v.usage_limit }),
            };
        });

    export type Outbound = {
        amount?: string | undefined;
        code?: string | null | undefined;
        currency_code?: CurrencyCode2 | undefined;
        description?: string | undefined;
        enabled_for_checkout: boolean;
        expires_at?: string | undefined;
        id?: string | undefined;
        maximum_recurring_intervals?: number | null | undefined;
        recur: boolean;
        restrict_to?: Array<string> | null | undefined;
        status?: SchemaStatusDiscount | undefined;
        type?: DiscountType | undefined;
        usage_limit?: number | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DiscountInput> = z
        .object({
            amount: z.string().optional(),
            code: z.nullable(z.string()).optional(),
            currencyCode: CurrencyCode2$.optional(),
            description: z.string().optional(),
            enabledForCheckout: z.boolean().default(true),
            expiresAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            id: z.string().optional(),
            maximumRecurringIntervals: z.nullable(z.number().int()).optional(),
            recur: z.boolean().default(false),
            restrictTo: z.nullable(z.array(z.string())).optional(),
            status: SchemaStatusDiscount$.optional(),
            type: DiscountType$.optional(),
            usageLimit: z.nullable(z.number().int()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.amount === undefined ? null : { amount: v.amount }),
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.currencyCode === undefined ? null : { currency_code: v.currencyCode }),
                ...(v.description === undefined ? null : { description: v.description }),
                enabled_for_checkout: v.enabledForCheckout,
                ...(v.expiresAt === undefined ? null : { expires_at: v.expiresAt }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.maximumRecurringIntervals === undefined
                    ? null
                    : { maximum_recurring_intervals: v.maximumRecurringIntervals }),
                recur: v.recur,
                ...(v.restrictTo === undefined ? null : { restrict_to: v.restrictTo }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.usageLimit === undefined ? null : { usage_limit: v.usageLimit }),
            };
        });
}
