/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum StatusDiscount {
    Active = "active",
    Archived = "archived",
    Expired = "expired",
    Used = "used",
}
