/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Return entities that match the specified status. Use a comma separated list to specify multiple status values.
 */
export enum StatusAdjustment {
    Approved = "approved",
    PendingApproval = "pending_approval",
    Rejected = "rejected",
    Reversed = "reversed",
}
