/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum StatusSubscription {
    Active = "active",
    Canceled = "canceled",
    PastDue = "past_due",
    Paused = "paused",
    Trialing = "trialing",
}
