/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Public URLs that customers can use to make changes to this subscription.
 */
export class SubscriptionManagementUrls extends SpeakeasyBase {
    /**
     * Public URL that lets customers cancel this subscription.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cancel" })
    cancel: string;

    /**
     * Public URL that lets customers update the payment method for this subscription.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "update_payment_method" })
    updatePaymentMethod?: string;
}
