/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Product } from "./product";
import { Totals1 } from "./totals1";
import { UnitTotals } from "./unittotals";
import { Expose, Type } from "class-transformer";

/**
 * Information about line items for this transaction preview. Different from transaction preview `items` as they include totals calculated by Paddle. Considered the source of truth for line item totals.
 */
export class TransactionPreviewLineItem extends SpeakeasyBase {
    /**
     * Unique Paddle ID for this price, prefixed with `pri_`.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "price_id" })
    priceId?: string;

    /**
     * Represents a product entity.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "product" })
    @Type(() => Product)
    product?: Product;

    /**
     * Quantity of this transaction line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity?: number;

    /**
     * Rate used to calculate tax for this transaction line item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "tax_rate" })
    taxRate?: string;

    /**
     * Breakdown of a charge in the lowest denomination of a currency (e.g. cents for USD).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "totals" })
    @Type(() => Totals1)
    totals?: Totals1;

    /**
     * Breakdown of the charge for one unit in the lowest denomination of a currency (e.g. cents for USD).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "unit_totals" })
    @Type(() => UnitTotals)
    unitTotals?: UnitTotals;
}
