/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CountryCode2 } from "./countrycode2";
import { Money2 } from "./money2";
import { Expose, Type } from "class-transformer";

export class UnitPriceOverride extends SpeakeasyBase {
    /**
     * Supported two-letter ISO 3166-1 alpha-2 country code. Customers located in the listed countries are charged the override price.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "country_codes" })
    countryCodes: CountryCode2[];

    @SpeakeasyMetadata()
    @Expose({ name: "unit_price" })
    @Type(() => Money2)
    unitPrice: Money2;
}
