/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { ErrorT } from "./error";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose, Type } from "class-transformer";

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(
        err?: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody
    ) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name =
            "GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody.prototype
        );
    }
}

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(
        err?: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody
    ) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name =
            "GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody.prototype
        );
    }
}

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(err?: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody.prototype
        );
    }
}

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(err?: GetSubscriptionUpdatePaymentMethodTransactionResponseBody) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "GetSubscriptionUpdatePaymentMethodTransactionResponseBody";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransactionResponseBody.prototype
        );
    }
}
