/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { ErrorT } from "./error";
import { AxiosResponse } from "axios";
import { classToPlain, Exclude, Expose, Type } from "class-transformer";

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransaction500ApplicationJSON extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(err?: GetSubscriptionUpdatePaymentMethodTransaction500ApplicationJSON) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "GetSubscriptionUpdatePaymentMethodTransaction500ApplicationJSON";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransaction500ApplicationJSON.prototype
        );
    }
}

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransaction409ApplicationJSON extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(err?: GetSubscriptionUpdatePaymentMethodTransaction409ApplicationJSON) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "GetSubscriptionUpdatePaymentMethodTransaction409ApplicationJSON";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransaction409ApplicationJSON.prototype
        );
    }
}

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransaction403ApplicationJSON extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(err?: GetSubscriptionUpdatePaymentMethodTransaction403ApplicationJSON) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "GetSubscriptionUpdatePaymentMethodTransaction403ApplicationJSON";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransaction403ApplicationJSON.prototype
        );
    }
}

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransaction401ApplicationJSON extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    @Exclude()
    rawResponse?: AxiosResponse;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrorT)
    error?: ErrorT;

    constructor(err?: GetSubscriptionUpdatePaymentMethodTransaction401ApplicationJSON) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "GetSubscriptionUpdatePaymentMethodTransaction401ApplicationJSON";
        Object.setPrototypeOf(
            this,
            GetSubscriptionUpdatePaymentMethodTransaction401ApplicationJSON.prototype
        );
    }
}
