/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ErrorT, ErrorT$ } from "./error";
import { z } from "zod";

/**
 * General error response
 */
export type GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBodyData =
    {
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        rawResponse?: Response | undefined;
        error?: ErrorT | undefined;
    };

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBodyData;

    constructor(
        err: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBodyData
    ) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name =
            "GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody";
    }
}

/**
 * General error response
 */
export type GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBodyData = {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;
};

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBodyData;

    constructor(
        err: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBodyData
    ) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name =
            "GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody";
    }
}

/**
 * General error response
 */
export type GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBodyData = {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;
};

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBodyData;

    constructor(err: GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBodyData) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody";
    }
}

/**
 * General error response
 */
export type GetSubscriptionUpdatePaymentMethodTransactionResponseBodyData = {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;
};

/**
 * General error response
 */
export class GetSubscriptionUpdatePaymentMethodTransactionResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: GetSubscriptionUpdatePaymentMethodTransactionResponseBodyData;

    constructor(err: GetSubscriptionUpdatePaymentMethodTransactionResponseBodyData) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "GetSubscriptionUpdatePaymentMethodTransactionResponseBody";
    }
}

/** @internal */
export namespace GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody(
                {
                    ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                    ...(v.error === undefined ? null : { error: v.error }),
                }
            );
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody
    > = z
        .instanceof(
            GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponse500ResponseBody
        )
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}

/** @internal */
export namespace GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody(
                {
                    ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                    ...(v.error === undefined ? null : { error: v.error }),
                }
            );
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody
    > = z
        .instanceof(GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}

/** @internal */
export namespace GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody({
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                ...(v.error === undefined ? null : { error: v.error }),
            });
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody
    > = z
        .instanceof(GetSubscriptionUpdatePaymentMethodTransactionSubscriptionsResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}

/** @internal */
export namespace GetSubscriptionUpdatePaymentMethodTransactionResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetSubscriptionUpdatePaymentMethodTransactionResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new GetSubscriptionUpdatePaymentMethodTransactionResponseBody({
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                ...(v.error === undefined ? null : { error: v.error }),
            });
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetSubscriptionUpdatePaymentMethodTransactionResponseBody
    > = z
        .instanceof(GetSubscriptionUpdatePaymentMethodTransactionResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}
