/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ErrorT, ErrorT$ } from "./error";
import { z } from "zod";

/**
 * General error response
 */
export type PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBodyData =
    {
        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        rawResponse?: Response | undefined;
        error?: ErrorT | undefined;
    };

/**
 * General error response
 */
export class PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBodyData;

    constructor(
        err: PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBodyData
    ) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name =
            "PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody";
    }
}

/**
 * General error response
 */
export type PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBodyData = {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;
};

/**
 * General error response
 */
export class PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBodyData;

    constructor(
        err: PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBodyData
    ) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody";
    }
}

/**
 * General error response
 */
export type PostNotificationSettingsNotificationSettingIdReplayResponseBodyData = {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;
};

/**
 * General error response
 */
export class PostNotificationSettingsNotificationSettingIdReplayResponseBody extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    error?: ErrorT | undefined;

    /** The original data that was passed to this error instance. */
    data$: PostNotificationSettingsNotificationSettingIdReplayResponseBodyData;

    constructor(err: PostNotificationSettingsNotificationSettingIdReplayResponseBodyData) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.error != null) {
            this.error = err.error;
        }

        const msg = "message" in err && typeof err.message === "string" ? err.message : "";
        const { rawResponse, ...data } = err;
        const content = JSON.stringify(data);
        this.message = [msg, content].filter(Boolean).join("\n");

        this.name = "PostNotificationSettingsNotificationSettingIdReplayResponseBody";
    }
}

/** @internal */
export namespace PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody(
                {
                    ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                    ...(v.error === undefined ? null : { error: v.error }),
                }
            );
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody
    > = z
        .instanceof(
            PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseResponseBody
        )
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}

/** @internal */
export namespace PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody(
                {
                    ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                    ...(v.error === undefined ? null : { error: v.error }),
                }
            );
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody
    > = z
        .instanceof(PostNotificationSettingsNotificationSettingIdReplayNotificationsResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}

/** @internal */
export namespace PostNotificationSettingsNotificationSettingIdReplayResponseBody$ {
    export type Inbound = {
        RawResponse?: Response | undefined;
        error?: ErrorT$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        PostNotificationSettingsNotificationSettingIdReplayResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            error: ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return new PostNotificationSettingsNotificationSettingIdReplayResponseBody({
                ...(v.RawResponse === undefined ? null : { rawResponse: v.RawResponse }),
                ...(v.error === undefined ? null : { error: v.error }),
            });
        });
    export type Outbound = {
        RawResponse?: never | undefined;
        error?: ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        PostNotificationSettingsNotificationSettingIdReplayResponseBody
    > = z
        .instanceof(PostNotificationSettingsNotificationSettingIdReplayResponseBody)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    error: ErrorT$.outboundSchema.optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.rawResponse === undefined ? null : { RawResponse: v.rawResponse }),
                        ...(v.error === undefined ? null : { error: v.error }),
                    };
                })
        );
}
