/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export type CreateBusinessRequest = {
    businessCreate?: shared.BusinessCreate | undefined;
    /**
     * Paddle ID of the customer entity to work with.
     */
    customerId: string;
};

/**
 * Created
 */
export type CreateBusinessResponseBody = {
    /**
     * Represents a business entity.
     */
    data: shared.Business;
    /**
     * Information about this response.
     */
    meta: shared.Meta;
};

export type CreateBusinessResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Created
     */
    object?: CreateBusinessResponseBody | undefined;
};

/** @internal */
export namespace CreateBusinessRequest$ {
    export type Inbound = {
        "business-create"?: shared.BusinessCreate$.Inbound | undefined;
        customer_id: string;
    };

    export const inboundSchema: z.ZodType<CreateBusinessRequest, z.ZodTypeDef, Inbound> = z
        .object({
            "business-create": shared.BusinessCreate$.inboundSchema.optional(),
            customer_id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v["business-create"] === undefined
                    ? null
                    : { businessCreate: v["business-create"] }),
                customerId: v.customer_id,
            };
        });

    export type Outbound = {
        "business-create"?: shared.BusinessCreate$.Outbound | undefined;
        customer_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateBusinessRequest> = z
        .object({
            businessCreate: shared.BusinessCreate$.outboundSchema.optional(),
            customerId: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.businessCreate === undefined
                    ? null
                    : { "business-create": v.businessCreate }),
                customer_id: v.customerId,
            };
        });
}

/** @internal */
export namespace CreateBusinessResponseBody$ {
    export type Inbound = {
        data: shared.Business$.Inbound;
        meta: shared.Meta$.Inbound;
    };

    export const inboundSchema: z.ZodType<CreateBusinessResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: shared.Business$.inboundSchema,
            meta: shared.Meta$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: shared.Business$.Outbound;
        meta: shared.Meta$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateBusinessResponseBody> = z
        .object({
            data: shared.Business$.outboundSchema,
            meta: shared.Meta$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace CreateBusinessResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
        object?: CreateBusinessResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateBusinessResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => CreateBusinessResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
        object?: CreateBusinessResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateBusinessResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => CreateBusinessResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
