/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export type GetInvoicePdfRequest = {
    /**
     * Paddle ID of the invoice entity to work with.
     */
    invoiceId: string;
};

export type GetInvoicePdfData = {
    /**
     * URL of the requested resource.
     */
    url?: string | undefined;
};

/**
 * OK
 */
export type GetInvoicePdfResponseBody = {
    data: GetInvoicePdfData;
    /**
     * Information about this response.
     */
    meta: shared.Meta;
};

export type GetInvoicePdfResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    object?: GetInvoicePdfResponseBody | undefined;
};

/** @internal */
export namespace GetInvoicePdfRequest$ {
    export type Inbound = {
        invoice_id: string;
    };

    export const inboundSchema: z.ZodType<GetInvoicePdfRequest, z.ZodTypeDef, Inbound> = z
        .object({
            invoice_id: z.string(),
        })
        .transform((v) => {
            return {
                invoiceId: v.invoice_id,
            };
        });

    export type Outbound = {
        invoice_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetInvoicePdfRequest> = z
        .object({
            invoiceId: z.string(),
        })
        .transform((v) => {
            return {
                invoice_id: v.invoiceId,
            };
        });
}

/** @internal */
export namespace GetInvoicePdfData$ {
    export type Inbound = {
        url?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetInvoicePdfData, z.ZodTypeDef, Inbound> = z
        .object({
            url: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.url === undefined ? null : { url: v.url }),
            };
        });

    export type Outbound = {
        url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetInvoicePdfData> = z
        .object({
            url: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.url === undefined ? null : { url: v.url }),
            };
        });
}

/** @internal */
export namespace GetInvoicePdfResponseBody$ {
    export type Inbound = {
        data: GetInvoicePdfData$.Inbound;
        meta: shared.Meta$.Inbound;
    };

    export const inboundSchema: z.ZodType<GetInvoicePdfResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.lazy(() => GetInvoicePdfData$.inboundSchema),
            meta: shared.Meta$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: GetInvoicePdfData$.Outbound;
        meta: shared.Meta$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetInvoicePdfResponseBody> = z
        .object({
            data: z.lazy(() => GetInvoicePdfData$.outboundSchema),
            meta: shared.Meta$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace GetInvoicePdfResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
        object?: GetInvoicePdfResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetInvoicePdfResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetInvoicePdfResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
        object?: GetInvoicePdfResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetInvoicePdfResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetInvoicePdfResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
