/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export type GetPriceRequest = {
    /**
     * Include related entities in the response.
     */
    include?: shared.IncludePrice | undefined;
    /**
     * Paddle ID of the price entity to work with.
     */
    priceId: string;
};

/**
 * OK
 */
export type GetPriceResponseBody = {
    /**
     * Represents a price entity with included entities.
     */
    data: shared.PriceIncludes;
    /**
     * Information about this response.
     */
    meta: shared.Meta;
};

export type GetPriceResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    object?: GetPriceResponseBody | undefined;
};

/** @internal */
export namespace GetPriceRequest$ {
    export type Inbound = {
        include?: shared.IncludePrice | undefined;
        price_id: string;
    };

    export const inboundSchema: z.ZodType<GetPriceRequest, z.ZodTypeDef, Inbound> = z
        .object({
            include: shared.IncludePrice$.optional(),
            price_id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.include === undefined ? null : { include: v.include }),
                priceId: v.price_id,
            };
        });

    export type Outbound = {
        include?: shared.IncludePrice | undefined;
        price_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPriceRequest> = z
        .object({
            include: shared.IncludePrice$.optional(),
            priceId: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.include === undefined ? null : { include: v.include }),
                price_id: v.priceId,
            };
        });
}

/** @internal */
export namespace GetPriceResponseBody$ {
    export type Inbound = {
        data: shared.PriceIncludes$.Inbound;
        meta: shared.Meta$.Inbound;
    };

    export const inboundSchema: z.ZodType<GetPriceResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: shared.PriceIncludes$.inboundSchema,
            meta: shared.Meta$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: shared.PriceIncludes$.Outbound;
        meta: shared.Meta$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPriceResponseBody> = z
        .object({
            data: shared.PriceIncludes$.outboundSchema,
            meta: shared.Meta$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace GetPriceResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
        object?: GetPriceResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetPriceResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetPriceResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
        object?: GetPriceResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPriceResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetPriceResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
