/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export type ListAdjustmentsRequest = {
    /**
     * Return entities for the specified action.
     */
    action?: shared.Action | undefined;
    /**
     * Return entities after the specified cursor. Used for working through paginated results.
     */
    after?: string | undefined;
    /**
     * Return entities related to the specified customer. Use a comma separated list to specify multiple customer IDs.
     */
    customerId?: string | undefined;
    /**
     * Return only the IDs specified. Use a comma separated list to get multiple entities.
     */
    id?: string | undefined;
    /**
     * Order returned entities by the specified field and direction (`[ASC]` or `[DESC]`).
     */
    orderBy?: string | undefined;
    /**
     * Set how many entities are returned per page.
     */
    perPage?: number | undefined;
    /**
     * Return entities that match the specified status. Use a comma separated list to specify multiple status values.
     */
    status?: shared.StatusAdjustment | undefined;
    /**
     * Return entities related to the specified subscription. Use a comma separated list to specify multiple subscription IDs.
     */
    subscriptionId?: string | undefined;
    /**
     * Return entities related to the specified transaction. Use a comma separated list to specify multiple transaction IDs.
     */
    transactionId?: string | undefined;
};

/**
 * OK
 */
export type ListAdjustmentsResponseBody = {
    data: Array<shared.Adjustment2>;
    /**
     * Information about this response.
     */
    meta: shared.MetaPaginated;
};

export type ListAdjustmentsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    object?: ListAdjustmentsResponseBody | undefined;
};

/** @internal */
export namespace ListAdjustmentsRequest$ {
    export type Inbound = {
        action?: shared.Action | undefined;
        after?: string | undefined;
        customer_id?: string | undefined;
        id?: string | undefined;
        order_by?: string | undefined;
        per_page?: number | undefined;
        status?: shared.StatusAdjustment | undefined;
        subscription_id?: string | undefined;
        transaction_id?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ListAdjustmentsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            action: shared.Action$.optional(),
            after: z.string().optional(),
            customer_id: z.string().optional(),
            id: z.string().optional(),
            order_by: z.string().default("id[ASC]"),
            per_page: z.number().int().default(10),
            status: shared.StatusAdjustment$.optional(),
            subscription_id: z.string().optional(),
            transaction_id: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.action === undefined ? null : { action: v.action }),
                ...(v.after === undefined ? null : { after: v.after }),
                ...(v.customer_id === undefined ? null : { customerId: v.customer_id }),
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.order_by === undefined ? null : { orderBy: v.order_by }),
                ...(v.per_page === undefined ? null : { perPage: v.per_page }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.subscription_id === undefined ? null : { subscriptionId: v.subscription_id }),
                ...(v.transaction_id === undefined ? null : { transactionId: v.transaction_id }),
            };
        });

    export type Outbound = {
        action?: shared.Action | undefined;
        after?: string | undefined;
        customer_id?: string | undefined;
        id?: string | undefined;
        order_by: string;
        per_page: number;
        status?: shared.StatusAdjustment | undefined;
        subscription_id?: string | undefined;
        transaction_id?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListAdjustmentsRequest> = z
        .object({
            action: shared.Action$.optional(),
            after: z.string().optional(),
            customerId: z.string().optional(),
            id: z.string().optional(),
            orderBy: z.string().default("id[ASC]"),
            perPage: z.number().int().default(10),
            status: shared.StatusAdjustment$.optional(),
            subscriptionId: z.string().optional(),
            transactionId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.action === undefined ? null : { action: v.action }),
                ...(v.after === undefined ? null : { after: v.after }),
                ...(v.customerId === undefined ? null : { customer_id: v.customerId }),
                ...(v.id === undefined ? null : { id: v.id }),
                order_by: v.orderBy,
                per_page: v.perPage,
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.subscriptionId === undefined ? null : { subscription_id: v.subscriptionId }),
                ...(v.transactionId === undefined ? null : { transaction_id: v.transactionId }),
            };
        });
}

/** @internal */
export namespace ListAdjustmentsResponseBody$ {
    export type Inbound = {
        data: Array<shared.Adjustment2$.Inbound>;
        meta: shared.MetaPaginated$.Inbound;
    };

    export const inboundSchema: z.ZodType<ListAdjustmentsResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: z.array(shared.Adjustment2$.inboundSchema),
            meta: shared.MetaPaginated$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: Array<shared.Adjustment2$.Outbound>;
        meta: shared.MetaPaginated$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListAdjustmentsResponseBody> = z
        .object({
            data: z.array(shared.Adjustment2$.outboundSchema),
            meta: shared.MetaPaginated$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace ListAdjustmentsResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
        object?: ListAdjustmentsResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<ListAdjustmentsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => ListAdjustmentsResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
        object?: ListAdjustmentsResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListAdjustmentsResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => ListAdjustmentsResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
