/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export type UpdateDiscountRequest = {
    discount?: shared.DiscountInput | undefined;
    /**
     * Paddle ID of the discount entity to work with.
     */
    discountId: string;
};

/**
 * OK
 */
export type UpdateDiscountResponseBody = {
    /**
     * Represents a discount entity.
     */
    data: shared.Discount;
    /**
     * Information about this response.
     */
    meta: shared.Meta;
};

export type UpdateDiscountResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    headers: Record<string, Array<string>>;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * OK
     */
    object?: UpdateDiscountResponseBody | undefined;
};

/** @internal */
export namespace UpdateDiscountRequest$ {
    export type Inbound = {
        discount?: shared.DiscountInput$.Inbound | undefined;
        discount_id: string;
    };

    export const inboundSchema: z.ZodType<UpdateDiscountRequest, z.ZodTypeDef, Inbound> = z
        .object({
            discount: shared.DiscountInput$.inboundSchema.optional(),
            discount_id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.discount === undefined ? null : { discount: v.discount }),
                discountId: v.discount_id,
            };
        });

    export type Outbound = {
        discount?: shared.DiscountInput$.Outbound | undefined;
        discount_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateDiscountRequest> = z
        .object({
            discount: shared.DiscountInput$.outboundSchema.optional(),
            discountId: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.discount === undefined ? null : { discount: v.discount }),
                discount_id: v.discountId,
            };
        });
}

/** @internal */
export namespace UpdateDiscountResponseBody$ {
    export type Inbound = {
        data: shared.Discount$.Inbound;
        meta: shared.Meta$.Inbound;
    };

    export const inboundSchema: z.ZodType<UpdateDiscountResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            data: shared.Discount$.inboundSchema,
            meta: shared.Meta$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });

    export type Outbound = {
        data: shared.Discount$.Outbound;
        meta: shared.Meta$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateDiscountResponseBody> = z
        .object({
            data: shared.Discount$.outboundSchema,
            meta: shared.Meta$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                meta: v.meta,
            };
        });
}

/** @internal */
export namespace UpdateDiscountResponse$ {
    export type Inbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: Response;
        object?: UpdateDiscountResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateDiscountResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Headers: z.record(z.array(z.string())),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => UpdateDiscountResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                headers: v.Headers,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        Headers: Record<string, Array<string>>;
        StatusCode: number;
        RawResponse: never;
        object?: UpdateDiscountResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateDiscountResponse> = z
        .object({
            contentType: z.string(),
            headers: z.record(z.array(z.string())),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => UpdateDiscountResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                Headers: v.headers,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
