/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Addresses } from "./addresses";
import { Adjustments } from "./adjustments";
import { Businesses } from "./businesses";
import { Customers } from "./customers";
import { Discounts } from "./discounts";
import { Events } from "./events";
import { Invoices } from "./invoices";
import { IPAddresses } from "./ipaddresses";
import { Notifications } from "./notifications";
import { Prices } from "./prices";
import { Products } from "./products";
import { Subscriptions } from "./subscriptions";
import { Transactions } from "./transactions";

export class Paddle extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }

    private _adjustments?: Adjustments;
    get adjustments() {
        return (this._adjustments ??= new Adjustments(this.options$));
    }

    private _customers?: Customers;
    get customers() {
        return (this._customers ??= new Customers(this.options$));
    }

    private _addresses?: Addresses;
    get addresses() {
        return (this._addresses ??= new Addresses(this.options$));
    }

    private _businesses?: Businesses;
    get businesses() {
        return (this._businesses ??= new Businesses(this.options$));
    }

    private _discounts?: Discounts;
    get discounts() {
        return (this._discounts ??= new Discounts(this.options$));
    }

    private _events?: Events;
    get events() {
        return (this._events ??= new Events(this.options$));
    }

    private _invoices?: Invoices;
    get invoices() {
        return (this._invoices ??= new Invoices(this.options$));
    }

    private _ipAddresses?: IPAddresses;
    get ipAddresses() {
        return (this._ipAddresses ??= new IPAddresses(this.options$));
    }

    private _notifications?: Notifications;
    get notifications() {
        return (this._notifications ??= new Notifications(this.options$));
    }

    private _prices?: Prices;
    get prices() {
        return (this._prices ??= new Prices(this.options$));
    }

    private _transactions?: Transactions;
    get transactions() {
        return (this._transactions ??= new Transactions(this.options$));
    }

    private _products?: Products;
    get products() {
        return (this._products ??= new Products(this.options$));
    }

    private _subscriptions?: Subscriptions;
    get subscriptions() {
        return (this._subscriptions ??= new Subscriptions(this.options$));
    }
}
